package com.example.demoMysql.dao;

import com.example.demoMysql.bean.StudentEntity;
import com.example.demoMysql.bean.StudentEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    long countByExample(StudentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int deleteByExample(StudentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int insert(StudentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int insertSelective(StudentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    List<StudentEntity> selectByExample(StudentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    StudentEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") StudentEntity record, @Param("example") StudentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int updateByExample(@Param("record") StudentEntity record, @Param("example") StudentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int updateByPrimaryKeySelective(StudentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Aug 29 13:30:26 CST 2019
     */
    int updateByPrimaryKey(StudentEntity record);
}